services:
  bind9:
    image: internetsystemsconsortium/bind9:9.20
    container_name: bind9
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 953:953/tcp
    restart: unless-stopped
    command: -4 -g -c /etc/bind/named.conf
    volumes:
      - ./config:/etc/bind
