services:
  bind9:
    image: internetsystemsconsortium/bind9:9.20
    container_name: bind9
    ports:
      - 127.0.0.1:53:53/tcp
      - 127.0.0.1:53:53/udp
      - 127.0.0.1:953:953/tcp
    restart: unless-stopped
    command: -g -c /etc/bind/named.conf
    volumes:
      - ./config:/etc/bind
